import { spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const args = process.argv.slice(2);
if (args.includes('--version')) {
  process.stdout.write('codex-fixture 1.0.0\n');
  process.exit(0);
}
if (args.includes('--help') && args.includes('exec')) {
  process.stdout.write('Usage: codex exec [prompt]\n  --json  emit structured JSONL events\n');
  process.exit(0);
}
if (args[0] === 'models' || args.includes('models')) {
  process.stdout.write('{"models":[{"id":"fixture-model","name":"Fixture Model","thinkingEfforts":["auto"]}]}\n');
  process.exit(0);
}

const workspace = process.env.AGENTOS_WORKSPACE_ROOT ?? process.cwd();
const delayMs = Number(process.env.AGENTOS_FIXTURE_DELAY_MS ?? 20);
const emit = async value => {
  process.stdout.write(`${JSON.stringify(value)}\n`);
  await new Promise(resolve => setTimeout(resolve, Number.isFinite(delayMs) && delayMs >= 0 ? delayMs : 20));
};

await emit({ type: 'thread.started', thread_id: 'fixture-thread' });
await emit({ type: 'turn.started', turn_id: 'fixture-turn' });
await emit({ type: 'item.started', item: { id: 'tool-1', type: 'command_execution', command: 'npm test' } });

const executor = join(workspace, 'executor.ts');
writeFileSync(executor, readFileSync(executor, 'utf8').replace('1000', '2000'), 'utf8');
writeFileSync(join(workspace, 'architecture.md'), '# Runtime architecture\n\nGenerated by the Codex fixture.\n', 'utf8');
mkdirSync(join(workspace, 'artifacts'), { recursive: true });
writeFileSync(join(workspace, 'artifacts', 'demo.png'), Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',
  'base64',
));

const test = process.platform === 'win32'
  ? spawnSync('cmd.exe', ['/d', '/s', '/c', 'npm test'], { cwd: workspace, encoding: 'utf8', windowsHide: true })
  : spawnSync('npm', ['test'], { cwd: workspace, encoding: 'utf8', windowsHide: true });
await emit({
  type: 'item.completed',
  item: {
    id: 'tool-1',
    type: 'command_execution',
    status: test.status === 0 ? 'completed' : 'failed',
    exit_code: test.status ?? 1,
    aggregated_output: `${test.stdout ?? ''}${test.stderr ?? ''}`.trim(),
  },
});
await emit({
  type: 'item.completed',
  item: { id: 'message-1', type: 'agent_message', text: '已完成代码修改，并生成设计文档与测试报告。' },
});
await emit({ type: 'turn.completed', usage: { input_tokens: 12, output_tokens: 34 } });
